#rest:
  # you don't need to provide anything here - this channel doesn't
  # require any credentials
socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: false
#  cors_allowed_origins: []